insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('QD',N'Quyết định');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('HP',N'Hiến pháp');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('SL',N'Sắc lệnh-Sắc luật');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('L-PL',N'Luật-Pháp lệnh');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('ND',N'Nghị định');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('TT',N'Thông tư');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('CT',N'Chỉ thị');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('NQ',N'Nghị quyết');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('TB',N'Thông báo');
insert into loaicvs(MaLoaiCV,TenLoaiCV) values ('VB',N'Văn bản điều hành');