insert into phongbans(MaPB,TenPB) values ('PDT',N'Phòng đào tạo');
insert into phongbans(MaPB,TenPB) values ('PKHTC',N'Phòng kế hoạch tài chính');
insert into phongbans(MaPB,TenPB) values ('PHCTH',N'Phòng hành chính tổng hợp');
insert into phongbans(MaPB,TenPB) values ('PTCCB',N'Phòng tổ chức cán bộ');
insert into phongbans(MaPB,TenPB) values ('PCTHSSV',N'Phòng công tác HSSV');
insert into phongbans(MaPB,TenPB) values ('PQTTB',N'Phòng Quản trị thiết bị');
insert into phongbans(MaPB,TenPB) values ('PKHCN',N'Phòng Khoa học - Công nghệ');
insert into phongbans(MaPB,TenPB) values ('PDTTC_TNGV',N'Phòng ĐT tại chức và TNGV');
insert into phongbans(MaPB,TenPB) values ('PKT_KDCLGD',N'Phòng khảo thí và KDCL giáo dục');
insert into phongbans(MaPB,TenPB) values ('PQHDN',N'Phòng Quan hệ doanh nghiệp');
insert into phongbans(MaPB,TenPB) values ('PTT',N'Phòng thanh tra');
insert into phongbans(MaPB,TenPB) values ('PHRQT',N'Phòng hợp tác quốc tế');
insert into phongbans(MaPB,TenPB) values ('BCSHT',N'Ban hạ tâng cơ sở và XDCB');
insert into phongbans(MaPB,TenPB) values ('KSPKHTN',N'Khoa SP khoa học tự nhiên');
insert into phongbans(MaPB,TenPB) values ('KSPKHXH',N'Khoa SP khoa học xã hội');
insert into phongbans(MaPB,TenPB) values ('KTUD',N'Khoa toán - Ứng dụng');
insert into phongbans(MaPB,TenPB) values ('KGDTH',N'Khoa Giáo dục tiểu học');
insert into phongbans(MaPB,TenPB) values ('KGDMN',N'Khoa Giáo dục mầm non');
insert into phongbans(MaPB,TenPB) values ('KSPKT',N'Khoa sư phạm kỹ thuật');
insert into phongbans(MaPB,TenPB) values ('KNN',N'Khoa Ngoại ngữ');
insert into phongbans(MaPB,TenPB) values ('KMT',N'Khoa Mỹ thuật');
insert into phongbans(MaPB,TenPB) values ('KNT',N'Khoa Nghệ thuật');
insert into phongbans(MaPB,TenPB) values ('KCNTT',N'Khoa CNTT');
insert into phongbans(MaPB,TenPB) values ('KQTKD',N'Khoa Quản trị kinh doanh');
insert into phongbans(MaPB,TenPB) values ('KTVTT',N'Khoa Thư viện thông tin');
insert into phongbans(MaPB,TenPB) values ('KVHDL',N'Khoa Văn hóa du lịch');
insert into phongbans(MaPB,TenPB) values ('KTCKT',N'Khoa Tài chính kế toán');
insert into phongbans(MaPB,TenPB) values ('KKHMT',N'Khoa Khoa học môi trường');
insert into phongbans(MaPB,TenPB) values ('KQLGD',N'Khoa Quản lý giáo dục');
insert into phongbans(MaPB,TenPB) values ('KGDCT',N'Khoa Giáo dục chính trị');
insert into phongbans(MaPB,TenPB) values ('KL',N'Khoa Luật');
insert into phongbans(MaPB,TenPB) values ('LDTVT',N'Khoa Điện tử viễn thông');
insert into phongbans(MaPB,TenPB) values ('BMTT',N'Bộ môn trực thuộc');